config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :books do
    resources :comments
  end

  resources :collections

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
end

app/models/collection_item.rb
class CollectionItem < ActiveRecord::Base
  belongs_to :book
  belongs_to :collection
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def new
     @book = Book.new
  end
  
  def edit
    @book = Book.find(params[:id])
  end

  def show
    @book = Book.find(params[:id])
    #render plain: @book.inspect
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
   
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :text)
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  def index
    @collections = Collection.all
  end

  def new
    @collection = Collection.new
  end
  
  def edit
    @collection = Collection.find(params[:id])
  end

  def show
    @collection = Collection.find(params[:id])
  end

  def create
    @collection = Collection.new(collection_params)
    if @collection.save
      redirect_to @collection
    else
      render 'new'
    end
  end
  
  def update
  end
  
  def destroy
  end

  private
  def collection_params
    params.require(:collection).permit(:title,:description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @user = current_user
    @comment = @book.comments.create(comment_params.merge(:user_id => current_user.id))
    redirect_to book_path(@book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = @book.comments.find(params[:id])
    @comment.destroy
    redirect_to book_path(@book)
  end
 
  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>
<%= link_to 'New book', new_book_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.text %></td>
      <td><%= link_to 'Show', book_path(book) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book_path(book),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<h2>Whatcha reading?</h2>
<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @book.text %>
</p>

<h2>Comments</h2>
<%= render @book.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/collections/_form.erb
<%= form_for @collection do |c| %>
 
  <p>
    <%= c.label :title %><br>
    <%= c.text_field :title %>
  </p>
 
  <p>
    <%= c.label :description %><br>
    <%= c.text_area :description %>
  </p>
 
  <p>
    <%= c.submit %>
  </p>
 
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<h2>All Collections</h2>
<%= link_to 'New collection', new_collection_path %>
<% @collections.each do |collection| %>
  <p><%= collection.title %> <%= link_to 'Show', collection_path(collection) %> <%= link_to 'Edit', edit_collection_path(collection) %> <%= link_to 'Destroy', collection_path(collection),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></p>
<% end %>

app/views/collections/new.html.erb
<h2>New Collection!</h2>
<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @collection.title %>
</p>
 
<p>
  <strong>description:</strong>
  <%= @collection.description %>
</p>

<%= link_to 'Back', collections_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <% unless comment.user.nil? %>
    <%= comment.user.email %>
    <%= gravatar_image_tag(comment.user.email) %>
  <% end %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
<%= link_to 'Destroy Comment', [comment.book, comment],
             method: :delete,
             data: { confirm: 'Are you sure?' } %>		
</p>

app/views/comments/_form.html.erb
<%= form_for([@book, @book.comments.build]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookClub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<% if user_signed_in? %>
  <p>Logged in as <strong><%= current_user.email %></strong>.</p>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>This should be the homepage.</h1>
<%= link_to 'My Books', controller: 'books' %>
<%= link_to 'New Book', new_book_path %>